### ISSUE TITLE
Plugins are not working

### ISSUE THREAD

**Issue by XibalbaM** [deiv/ngx-markdown-it#4]
I import the module like that : 
`NgxMarkdownItModule.forRoot({plugins: [(test: MarkdownIt) => console.log('test')]})`
But there is no print in the console, even though markdown is properly displayed. Am I doing something bad ?

**Comment by deiv** [comment]
@XibalbaM seems that is not legal plugin for me.

**Comment by XibalbaM** [comment]
Yeah I put this just to test, but because the input type was any I thought that I was able to do that for debugging. I tried to use [this](https://gist.github.com/m93a/cedc4aae4d875f73305f841e919c857b), with just adding a console.log in the root and nothing append so I simplified it to check if the error wasn't from the example

**Comment by deiv** [comment]
The project contains a demo app with markmap plugin. Take a look ;)

**Comment by XibalbaM** [comment]
With `NgxMarkdownItModule.forRoot({plugins: [markmapPlugin]})` and the following content (without the backslashs they're just for github)
```
\```mindmap
# root
## child1
  - child3
## child2
  - child3
`\``
```
I get the following html in the markdown-it component, witch proves that the plugin isn't applied :
```html
<pre>
<code class="language-mindmap"># root
## child1
  - child3
## child2
  - child3
</code>
</pre>
```
For instance, the related versions of dependencies :
"@angular/core": "^16.2.11",
"markdown-it": "^13.0.2",
"markdown-it-markmap": "^0.1.0",
"ngx-markdown-it": "^16.0.1"

In my template, the component is used like this : `<markdown-it [markdown]="notes" class="inline"/>`. The inline class just set it to display: inline but removing it doesn't change anything

The module where the import is made is lazy loaded, but I don't think it's a problem. I created the markdown-it-markmap.d.ts file to declare the module for ts.

If other informations are needed don't hesitate to ask me 😄

**Comment by deiv** [comment]
Its normal, the markmap plugin needs:

```
<script src="https://cdn.jsdelivr.net/npm/d3@5"></script> <script src="https://cdn.jsdelivr.net/npm/markmap-lib@0.7.4/dist/browser/view.min.js"></script> <script> const mindmaps = document.querySelectorAll('.markmap-svg'); for(const mindmap of mindmaps) { markmap.markmap(mindmap, JSON.parse(mindmap.innerHTML)); } </script>
```

May you use the project example code?, ot should work fine ;)

**Comment by XibalbaM** [comment]
Okay so I'll use an [official plugin](https://github.com/markdown-it/markdown-it-sub) : with 
`NgxMarkdownItModule.forRoot({plugins: [markdownItSub]})` 
`import markdownItSub from "markdown-it-sub"`, 
`H~2~O` isn't transformed. What am I doing wrong ?

**Comment by deiv** [comment]
@XibalbaM 

For me, running the demo project (the root project in the repo), all is working as expected.

Could you please take the demo as reference ?

**Comment by XibalbaM** [comment]
I tried but the setup seems hard (just cloned, ran npm install and npm start and had many errors). I prefer to avoid learning to use a library just for a demo, that's why I choose to use an easier plugin. But if there's no other way I'll do it

**Comment by deiv** [comment]
Running the demo should be as easy as you have done... Maybe you have something broken :)

**Comment by XibalbaM** [comment]
Ran exactly what I said above on another device, and :
```
Error: src/app/app.module.ts:7:37 - error TS2307: Cannot find module 'ngx-markdown-it' or its corresponding type declarations.

7 import { NgxMarkdownItModule } from "ngx-markdown-it";
```

**Comment by XibalbaM** [comment]
Ok my bad, by replacing the local dependency by a normal one, it works perfectly. I'll investigate

**Comment by deiv** [comment]
My fault, we miss a step here. The demo points by default to the local lib build, so you new to build the lib first (or use the npm published one)

**Comment by XibalbaM** [comment]
Oh that's it
I'll tell you when the problem is solved

**Comment by deiv** [comment]
By the way, did you try the stackblitz demo https://stackblitz.com/edit/ngx-markdown-it ?

**Comment by XibalbaM** [comment]
Okay I fixed the problem. It's very weird: I was importing NgxMarkdownItModule in a lazy loaded module. I was not able to import it anywhere else because in a shared module I had an error telling that it was imported multiple times and in app module it wasn't available in my lazy module. I made my lazy module not lazy loaded, and the problem was fixed. Anyways thanks for the help !

**Comment by deiv** [comment]
Then, dont use `forRoot()`.
